// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';

function loadEnv() {
    const cwd = process.cwd();
    const isApiCwd = existsSync(resolve(cwd, 'prisma/schema.prisma'));

    const rootEnvPath = isApiCwd
        ? resolve(cwd, '../../.env')
        : resolve(cwd, '.env');
    const apiEnvPath = isApiCwd
        ? resolve(cwd, '.env')
        : resolve(cwd, 'apps/api/.env');

    config({ path: rootEnvPath });
    config({ path: apiEnvPath, override: true });
}

loadEnv();

function resolveDatasourceUrl() {
    if (process.env.DIRECT_URL) {
        return process.env.DIRECT_URL;
    }

    if (process.env.DATABASE_URL) {
        return process.env.DATABASE_URL.replace('-pooler.', '.');
    }

    throw new Error('DIRECT_URL or DATABASE_URL is required.');
}

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        url: resolveDatasourceUrl(),
    },
});
